const express = require("express")

const {connectedDb} = require("./config/db")
const UserRoute = require("./routes/user")
const app = express()
connectedDb()
app.use(express.json())
app.use("/user",UserRoute)
app.listen(3000,()=>console.log("server started")
)